version: '2'

services:
  codeception:
    image: gravityflow/codeception-extension
    #build: .
    depends_on:
      - wordpress
    environment:
      - GF_KEY=$GF_KEY
      - NO_CACHE_GRAVITY_FORMS=$NO_CACHE_GRAVITY_FORMS
      - NO_CACHE_GRAVITY_FLOW=$NO_CACHE_GRAVITY_FLOW
    volumes:
      - ./:/project
      - wp-core:/wp-core
      - ./:/wp-core/wp-content/plugins/example-step
    entrypoint: /docker-entrypoint.sh

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
      - chrome
    volumes:
      - wp-core:/var/www/html
      - ./:/var/www/html/wp-content/plugins/example-step
    ports:
      - 8080:80
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mariadb
    environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"

  chrome:
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
    image: selenium/standalone-chrome-debug:3.141.59-neon
    ports:
      - "4444:4444"
      - '5900:5900'
volumes:
  wp-core:
